language: java
jdk: openjdk6
sudo: false

before_install: chmod +x gradlew
install:
  - ./gradlew setupCIWorkspace -S
script:
  - ./gradlew build

cache:
  directories:
  - ~/.gradle

notifications:
  email: false
